name: Build

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
        - amd64
        - armhf
        - arm64
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v3
    - uses: diddlesnaps/snapcraft-multiarch-action@v1
      id: build
      with:
        architecture: ${{ matrix.platform }}
    - uses: diddlesnaps/snapcraft-review-action@v1
      with:
        snap: ${{ steps.build.outputs.snap }}
        isClassic: 'true'
    - uses: actions/upload-artifact@v4
      with:
        name: shellhub-agent-${{ matrix.platform }}
        path: ${{ steps.build.outputs.snap }}
      if: github.event_name == 'release' && !github.event.release.prerelease
    - uses: snapcore/action-publish@v1
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAP_STORE_LOGIN }}
      with:
        snap: ${{ steps.build.outputs.snap }}
        release: stable
      if: github.event_name == 'releasea' && !github.event.release.prerelease
